author:
  name: Gabriel Carneiro
  email: therealcarneiro@gmail.com

title: Aretha
email: arwtga@gmail.com
description: >-
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Suspendisse venenatis ligula et leo volutpat dapibus bibendum sit amet erat.
    Donec blandit laoreet consequat. Maecenas eu mi eu nisl gravida bibendum. Nam aliquet laoreet convallis. Curabitur consectetur tristique odio, sed vestibulum augue luctus ut. Morbi eget sollicitudin felis, a tempus sem. Duis tincidunt ex massa, id porttitor magna cursus quis. Vivamus rutrum nisl nunc, id volutpat velit feugiat id. Praesent finibus diam felis, eget tempus augue rhoncus non. 

baseurl: ""
url: "https://arwtga.github.io"
github_username: arwtga

# Build settings

plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-seo-tag

header_pages:
  - pages/index.html
  - pages/about.html
  - pages/publications.html
  - pages/education.html

collections_dir: collections

collections:
  education:
    output: true
    sort_by: start_year
    permalink: /:collection/:name

scholar:
  style: assets/csl/abnt.csl #apa  #chicago-fullnote-bibliography #apa

  sort_by: year, month
  order: descending # ascending
  group_by: year
  group_order: descending # ascending

  source: collections/_bib
  repository: papers
  bibliography: "*.bib"
  bibliography_template: bib #_layout/bib.html

  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
